### ISSUE TITLE
Alphabetise plugin and Kirby 2.0?

### ISSUE THREAD

**Issue by splorp** [shoesforindustry/kirbycms-extensions#4]
I am holding off migrating a couple of sites that use the Alphabetise plugin, mainly because I haven’t been able to test it with Kirby 2.0.

Do you know whether the existing plugin works with the current release of Kirby?

**Comment by shoesforindustry** [comment]
I did give it a quick go and it did work, but please try on a local test site copy first, as I've not done extensive testing.

**Comment by splorp** [comment]
Thanks for the quick test. I’ll be diving into this over the next few days.

**Comment by shoesforindustry** [comment]
Good luck! I should add I was using the old tag plugin for my test, not the new built in one because it doesn't have all the stuff I wanted to use. But it should work for the simpler page arrays too.

**Comment by shoesforindustry** [comment]
Sorry, forgot to close this
